### ISSUE TITLE
MavenCentral support.

### ISSUE THREAD

**Issue by pardom-zz** [guerwan/TransitionsBackport#4]
Please upload to MavenCentral! :smile:

**Comment by castorflex** [comment]
:+1:

**Comment by asarazan** [comment]
+1

**Comment by chrisjenx** [comment]
:+1:

**Comment by guerwan** [comment]
The library project is now on maven central : 
GroupId : com.guerwan
ArtifactId : transitionbackport
Version : 1.1

**Comment by myanimal** [comment]
@guerwan could you please publish a new version to maven central? Particularly the ArrayIndexOutOfBoundsException fix.

Thanks
